### ISSUE TITLE
[BUG] Not compiling

### ISSUE THREAD

**Issue by Official-Husko** [Funami580/sdl#1]
The program is not able to compile. It either throws async errors and it not being supported or if its removed then everything else cries. Also could you possibly provide pre-built binaries for windows?

**Comment by Funami580** [comment]
More information would be nice. What error exactly is shown? Did you use `cargo +nightly build --release`? The `+nightly` is important.

I haven't tested this program on windows, so I don't know whether pre-built binaries would work as intended. I feel like it's misleading to release windows binaries, anyway, as one would expect a flawless experience.

**Comment by Funami580** [comment]
https://github.com/Funami580/sdl/releases/tag/v0.1.0

**Comment by Official-Husko** [comment]
> More information would be nice. What error exactly is shown? Did you use `cargo +nightly build --release`? The `+nightly` is important.
> 
> I haven't tested this program on windows, so I don't know whether pre-built binaries would work as intended. I feel like it's misleading to release windows binaries, anyway, as one would expect a flawless experience.

I'm sorry i haven't responded anymore. I was busy with other things and rust just flat out refused to work so i couldn't get the exact error message back. And if I'm honest i also just forgot about it.
  
  
> https://github.com/Funami580/sdl/releases/tag/v0.1.0

Thank you for compiling and releasing prebuilt executables.
