### ISSUE TITLE
Request: add support for Firefox (and other WebDrivers)

### ISSUE THREAD

**Issue by GravisZro** [Funami580/sdl#3]
I would very much like support to be added for Firefox. **geckodriver** is a Rust crate to that allows the use of W3C WebDriver interface so it shouldn't be a huge effort to add support.

There are also other browsers with WebDriver support so being able to specify which backend to use would be ideal.

**Comment by Funami580** [comment]
Why, though?

**Comment by GravisZro** [comment]
Because not everybody uses a blink-based browser, myself included.
