### ISSUE TITLE
Fails to detect anti-automation pages

### ISSUE THREAD

**Issue by GravisZro** [Funami580/sdl#5]
The site aniwave.to, employs anti-automation protection which I believe is through cloudfront. As a result, sdl fails entirely.
```
$ ./sdl-0.1.1-linux-x64 --type dub --lang english https://aniwave.to/watch/psycho-pass.mpp/ep-1
13:24:22.792 ERROR > Failed to get series info: failed to find title: an element could not be located on the page using the given search parameters: no such element: Unable to locate element: {"method":"css selector","selector":"h1.title"}
  (Session info: chrome=116.0.5845.96)
```

**Comment by Funami580** [comment]
Just tried it on my side and it worked. Do you use a VPN? For some reason they seem to be suspicious of you.

**Comment by GravisZro** [comment]
I do use a VPN. They use cloudflare (not cloudfront).

**Comment by Funami580** [comment]
In that case turn off your VPN.

**Comment by GravisZro** [comment]
That's like telling someone to disable antivirus protection to use a program. Failing to detect Cloudflare's anti-automation is actual problem.

**Comment by Funami580** [comment]
Sure, but I'm not your servant. The main reason I wrote this program is for my use, not for others. If you want to have this feature, either modify the program to your needs, use some other program, or use torrents.

**Comment by GravisZro** [comment]
I understand entirely. Would ask that this ticket be tagged with **EWONTFIX** to avoid future confusion.

**Comment by Funami580** [comment]
Ok done :+1:
