### ISSUE TITLE
Could not compile

### ISSUE THREAD

**Issue by sufehmi** [Funami580/sdl#6]
Hi, tried to build, but failed at very near the end with the following error.

I'm wondering if the architecture is the reason (ubuntu arm, it's a VM running on Macbook M2)

Thanks.

=====

ubuntu@u22arm:~/tmp/sdl-main$ cargo build --release
   Compiling sdl v0.1.1 (/home/ubuntu/tmp/sdl-main)
error: could not compile `sdl` (bin "sdl")

Caused by:
  process didn't exit successfully: `rustc --crate-name sdl --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=132 --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=0c6589e8e568307e -C extra-filename=-0c6589e8e568307e --out-dir /home/ubuntu/tmp/sdl-main/target/release/deps -L dependency=/home/ubuntu/tmp/sdl-main/target/release/deps --extern anyhow=/home/ubuntu/tmp/sdl-main/target/release/deps/libanyhow-54a2f3d0fbc096cd.rlib --extern arc4=/home/ubuntu/tmp/sdl-main/target/release/deps/libarc4-028fe8b89be3c2a8.rlib --extern async_compression=/home/ubuntu/tmp/sdl-main/target/release/deps/libasync_compression-b146b700b3a67837.rlib --extern base64=/home/ubuntu/tmp/sdl-main/target/release/deps/libbase64-b023df15ea65ba3a.rlib --extern bitmask_enum=/home/ubuntu/tmp/sdl-main/target/release/deps/libbitmask_enum-0d0f2720da0a63ba.so --extern bytes=/home/ubuntu/tmp/sdl-main/target/release/deps/libbytes-c242f5acbaf95594.rlib --extern chrono=/home/ubuntu/tmp/sdl-main/target/release/deps/libchrono-fded116b9000ea27.rlib --extern clap=/home/ubuntu/tmp/sdl-main/target/release/deps/libclap-bcc8911e020ebd27.rlib --extern console=/home/ubuntu/tmp/sdl-main/target/release/deps/libconsole-2b5fcc207606590d.rlib --extern dirs=/home/ubuntu/tmp/sdl-main/target/release/deps/libdirs-882c5f94f3298b47.rlib --extern enum_iterator=/home/ubuntu/tmp/sdl-main/target/release/deps/libenum_iterator-9219f1dfa31278f9.rlib --extern enum_dispatch=/home/ubuntu/tmp/sdl-main/target/release/deps/libenum_dispatch-54f3cb61fbfc66f3.so --extern env_logger=/home/ubuntu/tmp/sdl-main/target/release/deps/libenv_logger-f4025020b03c70c0.rlib --extern form_urlencoded=/home/ubuntu/tmp/sdl-main/target/release/deps/libform_urlencoded-6ded446262bb48c0.rlib --extern futures_util=/home/ubuntu/tmp/sdl-main/target/release/deps/libfutures_util-24c437ddec6ac079.rlib --extern indicatif=/home/ubuntu/tmp/sdl-main/target/release/deps/libindicatif-01fe64cdc4fc2bdd.rlib --extern interprocess=/home/ubuntu/tmp/sdl-main/target/release/deps/libinterprocess-d5bd29ed6eb3a3cf.rlib --extern log=/home/ubuntu/tmp/sdl-main/target/release/deps/liblog-d2b95f987322e45d.rlib --extern m3u8_rs=/home/ubuntu/tmp/sdl-main/target/release/deps/libm3u8_rs-89d21408237b73fb.rlib --extern number_prefix=/home/ubuntu/tmp/sdl-main/target/release/deps/libnumber_prefix-ee6b45e4e1af84d7.rlib --extern once_cell=/home/ubuntu/tmp/sdl-main/target/release/deps/libonce_cell-531a412119426094.rlib --extern pathsearch=/home/ubuntu/tmp/sdl-main/target/release/deps/libpathsearch-eaae3cfca6f0a336.rlib --extern portpicker=/home/ubuntu/tmp/sdl-main/target/release/deps/libportpicker-9e1e9e154bf311d3.rlib --extern rand=/home/ubuntu/tmp/sdl-main/target/release/deps/librand-8ba3918d9dd1ea58.rlib --extern regex=/home/ubuntu/tmp/sdl-main/target/release/deps/libregex-e8c1e2bc84d19fb5.rlib --extern reqwest=/home/ubuntu/tmp/sdl-main/target/release/deps/libreqwest-c14a21aadf4717bc.rlib --extern reqwest_partial_retry=/home/ubuntu/tmp/sdl-main/target/release/deps/libreqwest_partial_retry-b989f11e579a0844.rlib --extern reqwest_retry=/home/ubuntu/tmp/sdl-main/target/release/deps/libreqwest_retry-f9ea234a2b4607e6.rlib --extern rust_lapper=/home/ubuntu/tmp/sdl-main/target/release/deps/librust_lapper-e356eb957ba5a192.rlib --extern sdl=/home/ubuntu/tmp/sdl-main/target/release/deps/libsdl-d5f0e7ece60a4d46.rlib --extern selenium_manager=/home/ubuntu/tmp/sdl-main/target/release/deps/libselenium_manager-bf3033286f977836.rlib --extern serde_json=/home/ubuntu/tmp/sdl-main/target/release/deps/libserde_json-07a6b194da1a89c5.rlib --extern thirtyfour=/home/ubuntu/tmp/sdl-main/target/release/deps/libthirtyfour-72cafb47e2dc4ffc.rlib --extern tokio=/home/ubuntu/tmp/sdl-main/target/release/deps/libtokio-e52b12d274e35cb6.rlib --extern tokio_stream=/home/ubuntu/tmp/sdl-main/target/release/deps/libtokio_stream-f1980b766e1c1e32.rlib --extern tokio_util=/home/ubuntu/tmp/sdl-main/target/release/deps/libtokio_util-fb514641120857bb.rlib --extern url=/home/ubuntu/tmp/sdl-main/target/release/deps/liburl-64aa0bccd23be04e.rlib --extern zip_extensions=/home/ubuntu/tmp/sdl-main/target/release/deps/libzip_extensions-edf9374c60bd5f3e.rlib -L native=/home/ubuntu/tmp/sdl-main/target/release/build/ring-b74a361f9bd4c2d9/out -L native=/home/ubuntu/tmp/sdl-main/target/release/build/bzip2-sys-6c783adcbb6f3c62/out/lib -L native=/home/ubuntu/tmp/sdl-main/target/release/build/lzma-sys-dae25baaafb040d8/out -L native=/home/ubuntu/tmp/sdl-main/target/release/build/zstd-sys-6ea88b3c54656a22/out` (signal: 9, SIGKILL: kill)

**Comment by Funami580** [comment]
Is that the entire backtrace? No error messages, just this single message "process didn't exit successfully"?

**Comment by sufehmi** [comment]
Yes, unfortunately that's it.

Before it failed because it can't find SSL libraries, but that was easy, just typed "sudo apt-get install -y libssl-dev" in Terminal.

====
Currently I'm installing ubuntu x86 on my macbook M2, will let you know if then able to compile it successfully.

Thanks.

**Comment by sufehmi** [comment]
Have installed ubuntu x86 on macbook M2 as VM - and it compiled just fine.

So I think this is ARM-related issue probably.

Thanks.

**Comment by sufehmi** [comment]
Thanks.

**Comment by Funami580** [comment]
Nice to hear :slightly_smiling_face: :+1:
