### ISSUE TITLE
Always fails to get video url when downloading from aniwave.to

### ISSUE THREAD

**Issue by PurpleAce88** [Funami580/sdl#7]
I tried recompiling and I tried downloading several different animes, but every time I try downloading something it says `WARN  > Failed to download episode: failed to get video url for episode` My guess is that it's something changed with aniwave.

**Comment by Funami580** [comment]
Can't check since the site seems to be down right now

**Comment by Funami580** [comment]
Should hopefully be fixed with v0.1.2.

**Comment by PurpleAce88** [comment]
Yeah seems to be fixed.

**Comment by AbyssalSoda** [comment]
R.I.P. Aniwave o7
