### ISSUE TITLE
Dockerize application?

### ISSUE THREAD

**Issue by spinnaker1** [Funami580/sdl#8]
Hello @Funami580 ,

will there be a dockerized version of the application?
This would be very helpful.

Best regards,
Martin

**Comment by Funami580** [comment]
Works for me. Full error?

**Comment by spinnaker1** [comment]
_**Proxmox 8.2: Container Ubuntu 22.04 LTS**_



**Installation of "sdl"**
```
wget https://github.com/Funami580/sdl/releases/download/v0.1.3/sdl-0.1.3-linux-x64.gz
gzip -d sdl-0.1.3-linux-x64.gz
mv sdl-0.1.3-linux-x64.gz sdl
chmod 755 sdl
chmod +x sdl
mv sdl /usr/bin/

```

**_Trying to download series from s.to_**
```
root@sdl:~# sdl https://s.to/serie/stream/breaking-bad
xx:xx:xx.xxx INFO  > uBlock Origin not installed... Installing...
xx:xx:xx.xxx ERROR > Failed to create ChromeDriver: could not connect to ChromeDriver: error creating new session: webdriver server did not respond: error trying to connect: tcp connect error: Connection refused (os error 111): webdriver server did not respond: error trying to connect: tcp connect error: Connection refused (os error 111)
```


On my laptop (Ubuntu 22.04 Desktop GUI) it works without issues.

**Comment by spinnaker1** [comment]
> Works for me. Full error?

i re-installed google-chrome and chromedriver. now it works. Still dockerized version would be awesome. :)

**Comment by Funami580** [comment]
Nice! I don't feel any personal motivation to create a docker version, but feel free to do so yourself.
